name: Build and Test

on:
  push:
    branches: [ main, dev, api-gateway ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CONNECTION_STRING: "Host=postgres;Database=tasks;Username=postgres;Password=postgres"
      SPEECH_PROCESSING_SERVICE_URI: "http://speech-processing-service:8080/api/speech/command/process"
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GIGACHAT_AUTH_TOKEN: ${{ secrets.GIGACHAT_AUTH_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      ASPNETCORE_ENVIRONMENT: Development

    steps:
      - uses: actions/checkout@v4

      - name: Docker compose up (build)
        uses: hoverkraft-tech/compose-action@v2.4.3
        with:
          compose-file: "./docker/docker-compose.yml"

      - name: Docker logs (on failure)
        if: failure()
        run: docker compose -f ./docker/docker-compose.yml logs --no-color

      - name: Docker compose down
        if: always()
        run: docker compose -f ./docker/docker-compose.yml down -v

  automated-api-tests:
    runs-on: ubuntu-latest
    needs: build

    env:
      CONNECTION_STRING: "Host=postgres;Database=tasks;Username=postgres;Password=postgres"
      SPEECH_PROCESSING_SERVICE_URI: "http://speech-processing-service:8080/api/speech/command/process"
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GIGACHAT_AUTH_TOKEN: ${{ secrets.GIGACHAT_AUTH_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      ASPNETCORE_ENVIRONMENT: Development

    steps:
      - uses: actions/checkout@v4

      - name: Docker compose up (tests)
        uses: hoverkraft-tech/compose-action@v2.4.3
        with:
          compose-file: "./docker/docker-compose.yml"

      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Postman login
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "45407659-053089c9-3b47-4fb8-969a-8a48adca8350" \
            -e "45407659-afb6e126-99e1-42f6-be4b-8766f390e465"

      - name: Docker logs (on failure)
        if: failure()
        run: docker compose -f ./docker/docker-compose.yml logs --no-color

      - name: Docker compose down
        if: always()
        run: docker compose -f ./docker/docker-compose.yml down -v