name: .NET

on:
  push:
    branches: [ $default-branch, api-gateway ]
  pull_request:
    branches: [ $default-branch, api-gateway ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        dotnet restore SpeechProcessingService/SpeechProcessingService.sln
        dotnet restore TaskManager/TaskManager.sln
    - name: Build
      run: |
        dotnet build --no-restore SpeechProcessingService/SpeechProcessingService.sln
        dotnet build --no-restore TaskManager/TaskManager.sln