name: Build n Test

on:
  push:
    branches: [ main, api-gateway ]
  pull_request:
    branches: [ main, api-gateway ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONNECTION_STRING: "Host=postgres;Database=tasks;Username=postgres;Password=postgres"
      SPEECH_PROCESSING_SERVICE_URI: "http://speech-processing-service:8080/api/speech/command/process"
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GIGACHAT_AUTH_TOKEN: ${{ secrets.GIGACHAT_AUTH_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      ASPNETCORE_ENVIRONMENT: "Development"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@05da55b2bb8a5a759d1c4732095044bd9018c050 # v2.4.3
        with:
          compose-file: "./docker/docker-compose.yml"
  
  automated-api-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "45407659-053089c9-3b47-4fb8-969a-8a48adca8350" -e "45407659-afb6e126-99e1-42f6-be4b-8766f390e465"